apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
        - name: logger
          image: mingrammer/flog
          args:
            - --format=json
            - --loop
            - --delay=500ms
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
